# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/dell/RAM/RAM.cache/wt [current_project]
set_property parent.project_path C:/Users/dell/RAM/RAM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/dell/RAM/RAM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/8bitscter.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/Dcode.v
  C:/Users/dell/multiplier/multiplier.srcs/sources_1/new/FA.v
  C:/Users/dell/multiplier/multiplier.srcs/sources_1/new/FA16.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/RAM128_8.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/RAM168.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/RAM2-8.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/RAM32_8.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/RAM4_8.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/RAM64_8.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/RAM8_8.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/RMblock.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/dff.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/dff8.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/dmux.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/multiplexer.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/muxx.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/muxx16.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/muxx32.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/muxx4.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/muxx8.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/opblock.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/reg2_8.v
  C:/Users/dell/RAM/RAM.srcs/sources_1/new/CPU.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/dell/RAM/RAM.srcs/constrs_1/new/reg2_8.xdc
set_property used_in_implementation false [get_files C:/Users/dell/RAM/RAM.srcs/constrs_1/new/reg2_8.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top CPU -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
